// Code generated by MockGen. DO NOT EDIT.
// Source: api.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	. "github.com/theplant/plantpkg/template"
	reflect "reflect"
)

// MockHelloService is a mock of HelloService interface
type MockHelloService struct {
	ctrl     *gomock.Controller
	recorder *MockHelloServiceMockRecorder
}

// MockHelloServiceMockRecorder is the mock recorder for MockHelloService
type MockHelloServiceMockRecorder struct {
	mock *MockHelloService
}

// NewMockHelloService creates a new mock instance
func NewMockHelloService(ctrl *gomock.Controller) *MockHelloService {
	mock := &MockHelloService{ctrl: ctrl}
	mock.recorder = &MockHelloServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHelloService) EXPECT() *MockHelloServiceMockRecorder {
	return m.recorder
}

// SayHello mocks base method
func (m *MockHelloService) SayHello(input *SayHelloInput) (*SayHelloResult, error) {
	ret := m.ctrl.Call(m, "SayHello", input)
	ret0, _ := ret[0].(*SayHelloResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SayHello indicates an expected call of SayHello
func (mr *MockHelloServiceMockRecorder) SayHello(input interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SayHello", reflect.TypeOf((*MockHelloService)(nil).SayHello), input)
}
